dist: trusty
sudo: required
language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install autoconf automake autopoint libtool libpam0g-dev bison flex gettext check
  - sudo apt-get install git && git clone https://github.com/dmage/kbd-test
before_script:
  - ./autogen.sh
script:
  - ./configure && make
  - make check
  - sudo ./src/loadkeys ./data/keymaps/i386/qwerty/us.map
  - cd kbd-test ; LOADKEYS='sudo ./../src/loadkeys' DUMPKEYS='sudo ./../src/dumpkeys' KBD_MODE='sudo ./../src/kbd_mode' ./hack/dump-keymaps.sh && diff -dur ./stabledump ./dump && echo "Dump has no difference with stable version"
